name: GetScreen Windows (6H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=sonicvibes01@gmail.com" > secrets.txt
      - name: Time Counter
        run: python time.py
